# Use the official Cypress base image (M1 compatible)
FROM cypress/included:10.3.0

# Copy the Cypress configuration file
COPY cypress.config.js .

# Copy the test specs
COPY cypress ./cypress

# Run the Cypress tests
CMD ["cypress", "run"]

# docker build -f ./frontend/Dockerfile.cypress -t testapp-cypress:latest ./frontend
# docker run --network=dev-net testapp-cypress